import Link from "next/link";

const Footer = () => {
  return (
    <footer>
      <div className="social-media">
        <h3>Share your experience</h3>
      </div>
      <div className="container">
        <div className="about">
          <Link href="/">
            <a className="nav-logo">Zapien</a>
          </Link>
          <p>
            The aim of our platform is to promote a sustainable lifestyle by
            providing a marketing tool that connects conscious brands and
            influencers. We want to spread awareness about the climate crisis
            and social issues through a successfully implemented marketing model
            that relies on daily content generated by inspiring and experienced
            “eco” influencers and content creators.
          </p>
        </div>
        <div className="footer-links">
          <div className="column1">
            <Link href="/">
              <a className="style-bold">About us</a>
            </Link>
            <Link href="/">
              <a>I am a Brand</a>
            </Link>
            <Link href="/">
              <a>I am a Conscious Creator</a>
            </Link>
          </div>
          <div className="column2">
            <Link href="/">
              <a className="style-bold">Contact Us</a>
            </Link>
            <Link href="/">
              <a className="style-bold">Privacy Policy</a>
            </Link>
            <Link href="/">
              <a className="style-bold">Terms</a>
            </Link>
          </div>
        </div>
      </div>
      <style jsx>{`
        .social-media {
          background-color: grey;
        }
      `}</style>
    </footer>
  );
};

export default Footer;
