import Link from "next/link";

const Footer = () => {
  return (
    <footer>
      <div className="container">
        <div className="info">
          <div className="about">
            <Link href="/">
              <a className="logo">Zapien</a>
            </Link>
            <p className="about-us-content">
              The aim of our platform is to promote a sustainable lifestyle by
              providing a marketing tool that connects conscious brands and
              influencers. We want to spread awareness about the climate crisis
              and social issues through a successfully implemented marketing
              model that relies on daily content generated by inspiring and
              experienced “eco” influencers and content creators.
            </p>
          </div>
          <div className="footer-links">
            <ul className="footer-linklist">
              <li>
                <Link href="/">
                  <a>About us</a>
                </Link>
              </li>
              <li>
                <Link href="/">
                  <a>I am a Brand</a>
                </Link>
              </li>
              <li>
                <Link href="/">
                  <a>I am a Conscious Creator</a>
                </Link>
              </li>
            </ul>
          </div>
          <div className="footer-links">
            <ul className="footer-linklist">
              <li>
                <Link href="/">
                  <a>Contact Us</a>
                </Link>
              </li>
              <li>
                <Link href="/">
                  <a>Privacy Policy</a>
                </Link>
              </li>
              <li>
                <Link href="/">
                  <a>Terms</a>
                </Link>
              </li>
            </ul>
          </div>
        </div>
        <div className="copyright">
          © 2020,
          <Link href="/">
            <a> Zapien</a>
          </Link>
        </div>
      </div>
      <style jsx>{`
        footer {
          margin-top: 20px;
          padding: 120px 0px;
          background-color: #f8f8f8;
          color: #333;
        }
        .info {
          display: grid;
          grid-template-columns: 50% 25% 25%;
        }

        .about {
          display: flex;
          flex-wrap: wrap;
        }

        .about-us-content {
          font-size: 12px;
          margin-top: 5px;
          text-align: justify;
          line-height: 1.5;
        }
        .footer-links {
          display: flex;
          padding-top: 36px;
          padding-left: 50px;
        }

        .footer-linklist {
          list-style: none;
          font-size: 12px;
        }
        .copyright {
          margin-top: 35px;
          font-size: 0.83333em;
        }
      `}</style>
    </footer>
  );
};

export default Footer;
